services:
  - type: web
    name: gemini-chat-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && langgraph up --config langgraph.json --port $PORT --host 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
